expiry_period_url = 10*366*24*60*60
KEY_LEN = 8

KEYDBNAME = 'key_db.db'
URLDBNAME = 'url_db.db'
SQLLITE_DB_PATH = 'urldb/'+URLDBNAME
SQLLITE_KEYDB_PATH = 'urldb/'+KEYDBNAME

KEYDB_CACHE_SIZE = 20
TOPK = 5

NO_OF_BUCKETS = 10
CACHE_SIZE = 100000
CACHE_SIZE_PER_BUCKETS = CACHE_SIZE/NO_OF_BUCKETS
